# pull official base image
FROM node:14.15.0

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn install
RUN npm ci --only=production

# add app
COPY . ./

EXPOSE 8011

# start app
CMD ["npm", "start"]