version: "3.9"

services:

  nerves.dev:
    container_name: nerves.dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 4211:4211
    environment:
      - CHOKIDAR_USEPOLLING=true